"""Initial migration.

Revision ID: 87dd2a6917e0
Revises: 
Create Date: 2024-06-19 14:58:48.739043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87dd2a6917e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_model',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Title', sa.String(length=200), nullable=False),
    sa.Column('Name', sa.String(length=200), nullable=False),
    sa.Column('Description', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('login_model',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Login', sa.String(length=200), nullable=False),
    sa.Column('Password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('sign_up_model',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=200), nullable=False),
    sa.Column('Login', sa.String(length=200), nullable=False),
    sa.Column('Password', sa.String(length=200), nullable=False),
    sa.Column('Role', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sign_up_model')
    op.drop_table('login_model')
    op.drop_table('data_model')
    # ### end Alembic commands ###
